cask_args force: true

brew "terraform"
brew "terraform_landscape"
brew "terragrunt"

brew "awscli"
brew "docker-credential-helper-ecr"
brew "dos2unix"

brew "hugo"
brew "postgresql@11"

brew "poetry"

cask "rectangle"

cask "powershell"

cask "microsoft-teams"

cask "drawio"
