cask_args force: true

brew "terraform"
brew "terraform_landscape"
brew "terragrunt"

brew "awscli"
brew "docker-credential-helper-ecr"
brew "dos2unix"

brew "hugo"

brew "postgresql"

cask "rectangle"

cask "powershell"
