- clean:
    ~/:
        force: true

- shell:
    - command: antibody bundle < plugins.txt > ~/.zsh/work-plugins.zsh
      stdout: true
      stderr: true

- link:
    ~/.gitconfig.extra:
      path: gitconfig.extra
      relink: true
    ~/.zsh/profiles/work-specific.zsh: work-specific.zsh
    ~/.config/starship.toml:
      path: starship.toml
      relink: true

# AWS docker credential helper: https://github.com/awslabs/amazon-ecr-credential-helper
# Setting up docker-credential-ecr-login doesn't work with MFA enabled.
# https://github.com/awslabs/amazon-ecr-credential-helper/issues/180
#
# Also: Docker desktop removes the link on restart
#    ~/.docker/config.json: docker_config.json


- brewfile:
    - "Brewfile"
