- clean:
    ~/:
        force: true

- shell:
    - command: antibody bundle < plugins.txt > ~/.zsh/work-plugins.zsh
      stdout: true
      stderr: true

- link:
    ~/.gitconfig.extra:
      path: gitconfig.extra
      relink: true
    ~/.zsh/profiles/work-specific.zsh: work-specific.zsh
    ~/.config/starship.toml:
      path: starship.toml
      relink: true


- brewfile:
    - "Brewfile"
