- clean:
    ~/:
        force: true

- link:
    ~/.gitconfig.extra:
      path: gitconfig.extra
      relink: true
    ~/.zsh/profiles/work-specific.zsh: work-specific.zsh

- brewfile:
    - "Brewfile"
