#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
PLUGINS_DIR="plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


function discover_plugins() {
    local plugins=""
    while read dir
    do
        plugins="${plugins} --plugin-dir=${PLUGINS_DIR}/${dir}"
    done <<< "$(ls ${PLUGINS_DIR})"
    echo ${plugins}
}

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${PLUGINS_DIR}"

plugin_opts=$(discover_plugins)
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" \
${plugin_opts} \
"${@}"
