#!/usr/bin/env bash

set -e

CONFIG_DIR="configs"
DOTBOT_DIR="dotbot"
PLUGINS_DIR="plugins"
PROFILES_DIR="profiles"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export BASEDIR

function print_usage() {
cat <<EOF
Usage: $0 {-p profile | -c config [...]}

Available profiles:
EOF
    ls -1 ${PROFILES_DIR}
}

function discover_plugins() {
    local plugins=""
    while read dir
    do
        plugins="${plugins} --plugin-dir=${PLUGINS_DIR}/${dir}"
    done <<< "$(ls ${PLUGINS_DIR})"
    echo ${plugins}
}

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${PLUGINS_DIR}"

while [[ $# -gt 0 ]]
do
    cmd="$1"
    case "$cmd" in
        (-h|--help)
            print_usage
            exit 0
            ;;
        (-p|--profile)
            shift
            PROFILE=$1
            shift
            ;;
        (-c|--config)
            shift
            CONFIGS+=" $1"
            shift
            ;;
        (*)
            print_usage
            exit 0
            ;;
    esac
done

if [[ -n ${PROFILE} ]]
then
    PROFILE_FILE=${PROFILES_DIR}/${PROFILE}

    if [[ ! -f ${PROFILE_FILE} ]]
    then
        echo "Invalid profile: ${PROFILE_FILE}"
        echo
        print_usage
        exit 1
    fi

    while IFS= read -r config; do
        CONFIGS+=" ${config}"
    done < "${PROFILE_FILE}"
fi

plugin_opts=$(discover_plugins)

echo -n "root password:"
read -s PW
export PW

for config in ${CONFIGS} ${@}; do
    echo -e "\n=== Configure $config ==="
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" --verbose -d "${CONFIG_DIR}/${config}" -c "${CONFIG_DIR}/${config}/dotbot.yaml" \
    ${plugin_opts} \
    "${@}"
done
