- brewfile:
    - "Brewfile"

- link:
    ~/.zsh/profiles/git.zsh: git.zsh
    ~/.gitconfig: gitconfig
    ~/bin/git-bin: bin
    ~/.gitconfig.extra:
        path: gitconfig.extra
        relink: true