tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# required by dotfiles installation/setup tools
brew "ansible"
brew "mas"

# terminal enhancements
cask "iterm2"

# password management
brew "lastpass-cli"
cask "lastpass"

# File search
brew "fd"
brew "ripgrep"

# http
brew "httpie"
brew "wget"
brew "curl"

# File cleanup
brew "ncdu"
brew "duc"
cask "appcleaner"

# System utilities
cask "gfxcardstatus"
cask "keepingyouawake"
brew "glances"
brew "htop"
# brew "zenith"
brew "watch"
brew "tldr"
brew "tree"
brew "bat"
brew "procs"
brew "bandwhich"
# brew "colordiff"
# brew "z"
# brew "zoxide"

# Touch bar utilities
# cask "touchswitcher"

# text/xml
brew "xml-coreutils"
brew "xmlstarlet"
brew "libxml2"

# browsers
cask "google-chrome"
cask "brave-browser"

# Benchmarking
# brew "hyperfine"

# Regex generator
brew "grex"

# Ref: https://zaiste.net/posts/shell-commands-rust/