- brewfile:
    - "Brewfile"

- link:
    ~/.zsh/profiles/go.zsh: go.zsh

- go:
    - github.com/spf13/cobra/cobra

# To install extra go tools:
# - go:
#   - github.com/delicb/cliware
#   -
#     package: github.com/delicb/cliware-middlewares
#     flags: [-v, -u]
#     stdout: true
#     stderr: true
