- hosts: localhost
  tasks:
    - name: Install kubectl krew plugin
      shell: |
        tmpdir="$(mktemp -d)"
        cd "${tmpdir}"
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/v0.3.2/krew.{tar.gz,yaml}"
        tar zxvf krew.tar.gz
        ./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" install --manifest=krew.yaml --archive=krew.tar.gz
        rm -rf "${tmpdir}"
      args:
        creates: "{{ lookup('env', 'HOME') }}/.krew"
