- brewfile:
    - "Brewfile"

- link:
    ~/.zsh/profiles/java.zsh: java.zsh

- shell:
    - command: curl -s "https://get.sdkman.io" | bash
      stdout: true
      stderr: true
    - command: ${BASEDIR}/ansible/run-ansible.sh
      stdout: true
      stderr: true

- link:
    ~/.sdkman/etc/config:
      path: sdkman
      force: true
