export PATH=${HOME}/bin:$PATH
export LANG=en_US.UTF-8

# Command tweaks
export LESS='-R -X -F' # configure-less

# Aliases
alias ls='ls -FG'

## History file configuration
[ -z "$HISTFILE" ] && export HISTFILE="$HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

# zgen plugin manager setup
export ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc)

# load zgenom
source "${HOME}/.zgenom/zgenom.zsh"

# Check for plugin and zgenom updates every 7 days
# This does not increase the startup time.
zgenom autoupdate

# if the init script doesn't exist
if ! zgenom saved; then
    echo "Creating a zgenom save"

    zgenom ohmyzsh

    # plugins
    zgenom ohmyzsh plugins/colored-man-pages
    zgenom load zsh-users/zsh-history-substring-search
    zgenom load zsh-users/zsh-syntax-highlighting

    # completions
    zgenom load zsh-users/zsh-completions src

    # theme
    # zgenom oh-my-zsh themes/arrow

    # save all to init script
    zgenom save

    # compile all zsh source scripts
    zgenom compile "$HOME/.zshrc"
    [[ -d ~/.zsh/profiles ]] && for P in ~/.zsh/profiles/*.zsh; do zgenom compile "$P"; done
fi

# Setup my own directory for completions.  fpath must be changed before calling compinit
fpath+=~/.zfunc

# Enable Completion
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

# Source all files in profiles dir
[[ -d ~/.zsh/profiles ]] && for P in ~/.zsh/profiles/*.zsh; do source $P; done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
