export PATH=${HOME}/bin:$PATH
export LANG=en_US.UTF-8

# Command tweaks
export LESS='-R -X -F' # configure-less

# Enable Completion
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

# Load zsh plugins (defined by running 'antibody bundle')
[[ -f ~/.zsh/plugins.zsh ]] && source ~/.zsh/plugins.zsh

# Source all files in profiles dir
[[ -d ~/.zsh/profiles ]] && for P in ~/.zsh/profiles/*.zsh; do source $P; done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
